### ISSUE TITLE
--with-sndfile-dir / Heroku

### ISSUE THREAD

**Issue by casiodk** [benalavi/waveform#19]
Im getting this error when trying to install ruby-audio on heroku

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
remote:
remote:        current directory:
remote:        /tmp/build_467cd00e8ccacb8c9e19a1c8f215801b/vendor/bundle/ruby/2.4.0/gems/ruby-audio-1.6.1/ext/rubyaudio_ext
remote:        /tmp/build_467cd00e8ccacb8c9e19a1c8f215801b/vendor/ruby-2.4.0/bin/ruby -r
remote:        ./siteconf20170402-221-1bofi0l.rb extconf.rb
remote:        checking for sndfile.h in /opt/local/include,/usr/local/include,C:/Program Files
remote:        (x86)/Mega-Nerd/libsndfile/include,C:/Program
remote:        Files/Mega-Nerd/libsndfile/include... no
remote:        checking for sf_open() in -lsndfile-1... no
remote:        checking for sf_open() in -lsndfile... no
remote:        *** extconf.rb failed ***
remote:        Could not create Makefile due to some reason, probably lack of necessary
remote:        libraries and/or headers.  Check the mkmf.log file for more details.  You may
remote:        need configuration options.
remote:
remote:        Provided configuration options:
remote:        --with-opt-dir
remote:        --without-opt-dir
remote:        --with-opt-include
remote:        --without-opt-include=${opt-dir}/include
remote:        --with-opt-lib
remote:        --without-opt-lib=${opt-dir}/lib
remote:        --with-make-prog
remote:        --without-make-prog
remote:        --srcdir=.
remote:        --curdir
remote:        --ruby=/tmp/build_467cd00e8ccacb8c9e19a1c8f215801b/vendor/ruby-2.4.0/bin/$(RUBY_BASE_NAME)
remote:        --with-sndfile-dir
remote:        --without-sndfile-dir
remote:        --with-sndfile-include
remote:        --without-sndfile-include=${sndfile-dir}/include
remote:        --with-sndfile-lib
remote:        --without-sndfile-lib=${sndfile-dir}/lib
remote:        --with-sndfile-1lib
remote:        --without-sndfile-1lib
remote:        --with-sndfilelib
remote:        --without-sndfilelib
remote:        extconf.rb:21:in `<main>':   Can't find libsndfile
remote:        (http://www.mega-nerd.com/libsndfile/) (RuntimeError)
remote:
remote:        Try passing --with-sndfile-dir or --with-sndfile-lib and
remote:        --with-sndfile-include
remote:        options to extconf. If there are spaces in the path on windows, it may not
remote:        work.
remote:
remote:        To see why this extension failed to compile, please check the mkmf.log which can
remote:        be found here:
remote:
remote:        /tmp/build_467cd00e8ccacb8c9e19a1c8f215801b/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/ruby-audio-1.6.1/mkmf.log
remote:
remote:        extconf failed, exit code 1
remote:
remote:        Gem files will remain installed in
remote:        /tmp/build_467cd00e8ccacb8c9e19a1c8f215801b/vendor/bundle/ruby/2.4.0/gems/ruby-audio-1.6.1
remote:        for inspection.
remote:        Results logged to
remote:        /tmp/build_467cd00e8ccacb8c9e19a1c8f215801b/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/ruby-audio-1.6.1/gem_make.out
remote:
remote:        An error occurred while installing ruby-audio (1.6.1), and Bundler cannot
remote:        continue.
remote:        Make sure that `gem install ruby-audio -v '1.6.1'` succeeds before bundling.
```

I have used this buildpack to install libsndfile : https://github.com/Soundtracktor/heroku-buildpack-libsndfile/blob/master/bin/compile

Do you have any suggestions?

**Comment by benalavi** [comment]
@casiodk I have not tried installing with that particular buildpack, but my guess would be that the buildpack installs the libsndfile libraries to a different location.

I have successfully installed this on Heroku using the Apt buildpack (https://github.com/heroku/heroku-buildpack-apt) which just installs packages for you using apt, and the ubuntu libsndfile package. My `Aptfile` contains:

```
libsndfile1
libsndfile1-dev
```

**Comment by casiodk** [comment]
I think the problem is not to install libsnd, but for ruby audio to install correctly

here is the out put with buildpack-apt as you suggested
```

Installing oily_png 1.2.1 with native extensions
remote:        Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
remote:
remote:        current directory:
remote:        /tmp/build_85c41f2386af4c7b610f59f77931d0d3/vendor/bundle/ruby/2.4.0/gems/ruby-audio-1.6.1/ext/rubyaudio_ext
remote:        /tmp/build_85c41f2386af4c7b610f59f77931d0d3/vendor/ruby-2.4.0/bin/ruby -r
remote:        ./siteconf20170402-220-6q418f.rb extconf.rb
remote:        checking for sndfile.h in /opt/local/include,/usr/local/include,C:/Program Files
remote:        (x86)/Mega-Nerd/libsndfile/include,C:/Program
remote:        Files/Mega-Nerd/libsndfile/include... no
remote:        checking for sf_open() in -lsndfile-1... no
remote:        checking for sf_open() in -lsndfile... no
remote:        *** extconf.rb failed ***
remote:        Could not create Makefile due to some reason, probably lack of necessary
remote:        libraries and/or headers.  Check the mkmf.log file for more details.  You may
remote:        need configuration options.
remote:
remote:        Provided configuration options:
remote:        --with-opt-dir
remote:        --without-opt-dir
remote:        --with-opt-include
remote:        --without-opt-include=${opt-dir}/include
remote:        --with-opt-lib
remote:        --without-opt-lib=${opt-dir}/lib
remote:        --with-make-prog
remote:        --without-make-prog
remote:        --srcdir=.
remote:        --curdir
remote:        --ruby=/tmp/build_85c41f2386af4c7b610f59f77931d0d3/vendor/ruby-2.4.0/bin/$(RUBY_BASE_NAME)
remote:        --with-sndfile-dir
remote:        --without-sndfile-dir
remote:        --with-sndfile-include
remote:        --without-sndfile-include=${sndfile-dir}/include
remote:        --with-sndfile-lib
remote:        --without-sndfile-lib=${sndfile-dir}/lib
remote:        --with-sndfile-1lib
remote:        --without-sndfile-1lib
remote:        --with-sndfilelib
remote:        --without-sndfilelib
remote:        extconf.rb:21:in `<main>':   Can't find libsndfile
remote:        (http://www.mega-nerd.com/libsndfile/) (RuntimeError)
remote:
remote:        Try passing --with-sndfile-dir or --with-sndfile-lib and
remote:        --with-sndfile-include
remote:        options to extconf. If there are spaces in the path on windows, it may not
remote:        work.
remote:
remote:        To see why this extension failed to compile, please check the mkmf.log which can
remote:        be found here:
remote:
remote:        /tmp/build_85c41f2386af4c7b610f59f77931d0d3/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/ruby-audio-1.6.1/mkmf.log
remote:
remote:        extconf failed, exit code 1
remote:
remote:        Gem files will remain installed in
remote:        /tmp/build_85c41f2386af4c7b610f59f77931d0d3/vendor/bundle/ruby/2.4.0/gems/ruby-audio-1.6.1
remote:        for inspection.
remote:        Results logged to
remote:        /tmp/build_85c41f2386af4c7b610f59f77931d0d3/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/ruby-audio-1.6.1/gem_make.out
remote:
remote:        An error occurred while installing ruby-audio (1.6.1), and Bundler cannot
remote:        continue.
remote:        Make sure that `gem install ruby-audio -v '1.6.1'` succeeds before bundling.
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to soundtracktor-api.
remote:
To https://git.heroku.com/soundtracktor-api.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/soundtracktor-api.git'
```

**Comment by casiodk** [comment]
Have you used this gem successfully on heroku?

**Comment by benalavi** [comment]
@casiodk Yes, I believe the `libsndfile` buildpack you are using is installing the libsndfile headers to a different location than rubygems expects them to be, so rubygems then cannot build ruby-audio.

I've used the gem on Heroku using the apt buildpack: https://github.com/benalavi/waveform/issues/19#issuecomment-291007893

**Comment by benalavi** [comment]
@casiodk Oh I'm sorry I misread your last comment, I didn't realize you were using the apt buildpack.

**Comment by casiodk** [comment]
I just tried with the buildpack you suggested... With the same result... But its weird I can install the gem like this : `heroku run gem install ruby-audio -v '1.6.1'` but not when i push to heroku

**Comment by benalavi** [comment]
@casiodk Are you using the other libsndfile buildpack as well?

**Comment by casiodk** [comment]
1. heroku/ruby
2. https://github.com/Soundtracktor/ffmpeg-lame-yasm
3. https://github.com/Soundtracktor/heroku-buildpack-apt

**Comment by casiodk** [comment]
im using another one for ffmpeg with lame-mp3

**Comment by casiodk** [comment]
i can try and remove that one. But how would you recommend installing ffmpeg... Also through the apt buildpack?

**Comment by casiodk** [comment]
no same result only with buildpack number 1 + 3

**Comment by benalavi** [comment]
@casiodk Are you using the new heroku ubuntu 16.04 stack by chance?

**Comment by casiodk** [comment]
No its the cedar-14

=== soundtracktor-api
Addons:         airbrake:free_heroku
                heroku-postgresql:hobby-dev
                heroku-redis:hobby-dev
                memcachier:100
                scheduler:standard
                sendgrid:starter
Auto Cert Mgmt: false
Dynos:          web: 1, worker: 1
Region:         eu
Repo Size:      84 MB
Slug Size:      163 MB
Stack:          cedar-14

**Comment by benalavi** [comment]
@casiodk ohhh, try putting the apt buildpack *before* the ruby buildpack, otherwise libsndfile will install *after* it tries to build gems

**Comment by benalavi** [comment]
@casiodk in fact that may have been the issue w/ the other libsndfile buildpack as well

**Comment by casiodk** [comment]
yes :) That makes sense

**Comment by casiodk** [comment]
I was also wondering why the gems was installed before the dependencies

**Comment by casiodk** [comment]
YES! Its working, thanks a lot. You are my hero :)

**Comment by benalavi** [comment]
@casiodk no problem, glad it worked!
